image: "ruby:3.2.2"

variables:
  RAILS_ENV: test

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler --no-document
  - bundle config set --local path 'vendor/ruby'
  - bundle install -j $(nproc)
  - bundle exec rake db:create db:schema:load db:migrate

test:
  script:
  - bundle exec rspec spec
